Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = :winrm
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"
  config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box_version = "1.0"
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./cookbooks/win10-chef/Berksfile"
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "win10-chef"
  end
end