# -*- mode: ruby -*-
# vi: set ft=ruby :

# Source https://github.com/rmaceissoft/sample-vagrant-windows/blob/master/Vagrantfile

Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = :winrm
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"
  config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box_version = "1.0"
  config.vm.network :private_network, ip: "192.168.16.27"
  # config.vm.box = "vagrant-win10-edge-64bit"
  # config.vm.box_url = "http://aka.ms/msedge.win10.vagrant"
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.memory = 8192
    vb.cpus = 2    
  end

  
  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
        "recipe[sample-vagrant-windows::default]"
    ]
  end
end